import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
// import Particles from "@/components/magicui/particles";
import { FloatingNav } from "@/components/ui/floating-navbar";
import NextTopLoader from "nextjs-toploader";
const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});
//TODO: Add data for seo
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const navItems = [
        {
            name: "Home",
            link: "/",
            //   icon: <IconHome className="h-4 w-4 text-neutral-500 dark:text-white" />,
        },
        {
            name: "Questions",
            link: "/questions",
            //   icon: <IconUser className="h-4 w-4 text-neutral-500 dark:text-white" />,
        },
        {
            name: "Contact",
            link: "/contact",
            //   icon: (
            //     // <IconMessage className="h-4 w-4 text-neutral-500 dark:text-white" />
            //   ),
        },
    ];
    return (
        <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NextTopLoader showSpinner={false} />
                {/* TODO:optimise nav for mobile view */}
                <FloatingNav navItems={navItems} />
                {children}
                <Toaster
                    toastOptions={{
                        style: {
                            background: "#1a1a1a",
                            color: "#e0e0e0",
                            borderColor: "#333",
                        },
                    }}
                />
            </body>
        </html>
    );
}
