import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";
import Header from "../components/home/Header";
import Footer from "@/components/home/Footer";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});
//TODO: Add data for seo
//TODO: add vercel analytics
//TODO: in google auth publish the app on google console and also add icon there in oAuth screen
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NextTopLoader showSpinner={false} />
                {/* TODO:optimise nav for mobile view */}
                {/* <FloatingNav navItems={navItems} /> */}
                <Header />
                {children}
                <Toaster
                    toastOptions={{
                        style: {
                            background: "#1a1a1a",
                            color: "#e0e0e0",
                            borderColor: "#333",
                        },
                    }}
                />
                <Footer />
            </body>
        </html>
    );
}
